### ISSUE TITLE
Implementation of Fragment.onCreateView with BindingPropertyDelegate

### ISSUE THREAD

**Issue by opengamer29** [kirich1409/ViewBindingPropertyDelegate#1]
Usual implementation approximately that way:
```
private var binding: ResultProfileBinding? = null

override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View = ResultProfileBinding.inflate(inflater, container, false).also {
    binding = it
}.root

override fun onDestroyView() {
    super.onDestroyView()
    binding = null
} 
```

But with BindingPropertyDelegate it looks like:
```
private val binding by viewBinding { fragment ->
        ResultProfileBinding.bind(fragment.requireView())
    }

override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View = inflater.inflate(R.layout.fragment_result_profile_binding, container, false)
```

As a result instead of using only one class ResultProfileBinding that encapsulate all layout info in one place, I have and ResultProfileBinding (with implicit ref to layout res) and explicit ref to layout res. I assume that there is a way to fetch ref to layout res from ResultProfileBinding static fields but I couldn't find it :(

Do you know that way? And how you usually implement onCreateView with BindingPropertyDelegate?

**Comment by kirich1409** [comment]
I recommend don't override `onCreateView` and use the constructor of `Fragment` that receive layout id as parameter

**Comment by kirich1409** [comment]
A `ViewBinding` can't be created without view of reference to layout id. It's limitation of the implementation.

**Comment by opengamer29** [comment]
Ok, got it. Thanks.
