### ISSUE TITLE
Make a separate artifacts for "reflection" and "general" approach

### ISSUE THREAD

**Issue by egorikftp** [kirich1409/ViewBindingPropertyDelegate#10]
I see that the library have the following proguard rule:

https://github.com/kirich1409/ViewBindingPropertyDelegate/blob/48d2e6e561c322d9f02365db388dffa899c8805e/library/proguard-rules.pro#L1

It prevents on obfuscation *ViewBinding classes. If I don't use reflection in delegate I expect that all my classes will be obfuscated.

The proposal is to make separate artefacts:

- _viewbindingpropertydelegate_ - regular logic, without reflection under the hood
- _viewbindingpropertydelegate-reflection_ - additional extensions for reflection approach + keep rule for ViewBinding classes.

Also with two artefacts, it will be clear for everyone what kind of delegate better to use and etc.

**Comment by kirich1409** [comment]
Will be added in 1.2.0
