### ISSUE TITLE
Failed to resolve: com.kirich1409.viewbindingpropertydelegate:vbpd-noreflection:1.2.0

### ISSUE THREAD

**Issue by Ant1kguild** [kirich1409/ViewBindingPropertyDelegate#15]
implementation 'com.kirich1409.viewbindingpropertydelegate:vbpd-noreflection:1.2.0' 
does not work

**Comment by wbervoets** [comment]
same here

**Comment by kirich1409** [comment]
I know about them. The problem caused by publishing on jcenter. As temporary fix you can add `https://dl.bintray.com/kirich1409/maven` to list of repositories

**Comment by kirich1409** [comment]
Is com.kirich1409.viewbindingpropertydelegate:viewbindingpropertydelegate:1.2.0' available ?

**Comment by wbervoets** [comment]
@kirich1409 no it also fails with "Failed to resolve: com.kirich1409.viewbindingpropertydelegate:vbpd-noreflection:1.2.0"

**Comment by wbervoets** [comment]
@kirich1409 the 1.0.0 version also fails now. Going to use the temporary fix for now

**Comment by kirich1409** [comment]
I am working on solving the issue. Temporary fix - add `https://dl.bintray.com/kirich1409/maven` to your repositories

**Comment by kirich1409** [comment]
The issue has been fixed

**Comment by SetareMaghari** [comment]
Its not fixed yet, i have this issue right now

**Comment by kirich1409** [comment]
It's problem with JCenter publishing. New versions will be available with delay

**Comment by SetareMaghari** [comment]
tnx. but what can i do now? adding this to repository didnt work: 
        maven("https://dl.bintray.com/kirich1409/maven/")   (dsl)

**Comment by kirich1409** [comment]
Try to add `maven { url = 'https://dl.bintray.com/kirich1409/maven' }`

**Comment by SetareMaghari** [comment]
no. it doesnt work too

**Comment by kirich1409** [comment]
@SetareMaghari check again with jcenter, please

**Comment by SetareMaghari** [comment]
yess, its working now. thank a bunch
