### ISSUE TITLE
ViewBinding can't be shared

### ISSUE THREAD

**Issue by yoobi** [kirich1409/ViewBindingPropertyDelegate#17]
Hello, 

I still got the issue #16  even with using 1.2.1 , I found that when I remove binding.rvSearchHistory.adapter = null from onDestroyView then it is working fine, but I can't really remove this line because it clears the reference to the adapter and prevent leaks in my application.

**Comment by kirich1409** [comment]
It will be good that you make sample project with the issue and I can reproduce it and than fix

**Comment by yoobi** [comment]
I've made a sample repository you can find it here https://github.com/yoobi/sampleViewBinding

**Comment by kirich1409** [comment]
Thanks. I'll check it

**Comment by kirich1409** [comment]
Fix will be in 1.2.2 in few hours

**Comment by andersu** [comment]
@kirich1409 I have the same issue. I see you fixed it in 1.2.2, but did you publish that version yet? I can't find it.
`Could not find com.kirich1409.viewbindingpropertydelegate:viewbindingpropertydelegate:1.2.2.`

**Comment by kirich1409** [comment]
Check it. Must be available

**Comment by andersu** [comment]
@kirich1409 it worked with `maven { url = 'https://dl.bintray.com/kirich1409/maven' }`
But not with just `jcenter()`

**Comment by kirich1409** [comment]
You can connect the repo directly, but it must be available from JCenter. I've checked
