### ISSUE TITLE
checkIsMainThread

### ISSUE THREAD

**Issue by CeH9** [kirich1409/ViewBindingPropertyDelegate#18]
Hi, nice lib. 
Isn't checkIsMainThread redundant? Android framework already has a lot of checks. You will got an exception if trying to touch views from another thread. 

Consider next snippet:
``` kt
binding.textView1.text = "blabla"
binding.textView3.text = "blabla"
binding.textView2.text = "blabla"
```

**Looper.getMainLooper()** contains synchronized block, seems like overhead for mentioned above case.

**Comment by kirich1409** [comment]
Hi. It was maid to guarantee proper initialization and clearing of the property. It can be replaced with own synchronization inside `ViewBindingPropertyDelegate`. I’ll think about that

**Comment by kirich1409** [comment]
Instead of your case I prefer to do next
```kotlin
with(binding) {
    textView1.text = "blabla"
    textView3.text = "blabla"
    textView2.text = "blabla"
}```

**Comment by CeH9** [comment]
> Instead of your case I prefer to do next
> 
> ```kotlin
> with(binding) {
>     textView1.text = "blabla"
>     textView3.text = "blabla"
>     textView2.text = "blabla"
> }
> ```

iirc compiler will unwrap it into my example (three independent calls)

**Comment by kirich1409** [comment]
Will be changed in 1.2.3
