### ISSUE TITLE
Can't access the Fragment View's LifecycleOwner when getView() is null

### ISSUE THREAD

**Issue by CeH9** [kirich1409/ViewBindingPropertyDelegate#19]
You can't access viewLifecycleOwner when **view** is null. Check should be inverted i.e. **!=**

``` kt
return if (thisRef.view == null) thisRef.viewLifecycleOwner else thisRef
```

https://github.com/kirich1409/ViewBindingPropertyDelegate/blob/master/vbpd/vbpd-noreflection/src/main/java/by/kirich1409/viewbindingdelegate/DialogFragmentViewBindings.kt#L16

**Comment by kirich1409** [comment]
This isn't mistake. It's handling case when an DialogFragment has custom view or not
