### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by Hero9909** [kirich1409/ViewBindingPropertyDelegate#2]
i would like to use this lib in a commercial project.
but im not allowed to use a lib without a license.
if you agree, i would be happy if you add a apache or mit license as  i could add the lib without a meeting.

**Comment by kirich1409** [comment]
Hi. Good point. I had plan to add it. I will do that in the begginig if the next week

**Comment by kirich1409** [comment]
Sorry, I forgot to do that (. License has been added to the project.
