### ISSUE TITLE
How to pass generic type to viewBindingDelegate

### ISSUE THREAD

**Issue by Berki2021** [kirich1409/ViewBindingPropertyDelegate#20]
I am trying to pass a generic type to the viewBinding Delegate, but it says: `Cannot use 'vb' as reified type parameter. Use a class instead`. Is this even possible?

```
abstract class BaseEmailFragment<out vb: ViewDataBinding>(
    layout: Int,
) : Fragment(layout) {

    private val binding by viewBinding<vb>() // Cannot use 'vb' as reified type parameter. Use a class instead.
}
```

**Comment by kirich1409** [comment]
viewBinding() requires to know exactly class of ViewBinding. I’ll make this improvements in next release

**Comment by kirich1409** [comment]
You need instance of Class if ViewBinding

**Comment by Berki2021** [comment]
Hmm okay, thank you for the fast reply! Is it possible to say, when the next release will be published? I am looking forward for this feature 👍

**Comment by kirich1409** [comment]
No. Right now you can do the next:
```kotlin

abstract class BaseEmailFragment<VB: ViewDataBinding>(
    layout: Int,
    vbClass: Class<VB>
) : Fragment(layout) {

    private val binding: VB by viewBinding(FragmentViewBinder(VB::class.java)::bind)
}

class FragmentViewBinder<T : ViewBinding>(private val viewBindingClass: Class<T>) {

    private companion object {
        val bindViewMethod by lazy(LazyThreadSafetyMode.NONE) {
            viewBindingClass.getMethod("bind", View::class.java)
        }
    }

    fun bind(fragment: Fragment): T {
        return bindViewMethod(null, fragment.requireView()) as T
    }
}

```

**Comment by Berki2021** [comment]
Thanks I will try it out. But `viewBindingClass.getMethod()` did not work when using it in combination with `private companion object`

**Comment by kirich1409** [comment]
Will be added in 1.3.0
