### ISSUE TITLE
VBPD not bind data to fragment when quickly switching between bottomNavBar tabs (with NavigationExtensions)

### ISSUE THREAD

**Issue by alexkopenkov** [kirich1409/ViewBindingPropertyDelegate#25]
Hello! You can see an example of an error in the repo https://github.com/alexkopenkov/Test.git

**Comment by kirich1409** [comment]
Hi. It must depend on the state of `LifecycleOwner`. Can be tricky

**Comment by kirich1409** [comment]
Hi. I can't reproduce the bug using the sample.

I need stacktrace with the error and device with OS version what you used for reproducing the bug

**Comment by danielchi0716** [comment]
simply add animations between fragment transitions could reproduce this bug

**Comment by alexkopenkov** [comment]
Using ViewBinding.inflate solves my problem.
