### ISSUE TITLE
Unexpected behavior on quick forward-back navigation in Fragments 

### ISSUE THREAD

**Issue by midery** [kirich1409/ViewBindingPropertyDelegate#35]
Hello! Thanks for the great library and simple approach for viewBinding initialization. 
I've discovered really annoying bug: if we will use fragment view bindings, try to replace current fragment with new fragment, and then quickly press back - our current fragment will not show all initialization data, which we will provide in it in `onCreateView` call. 

This happens because we're calling `handler.post { viewBinding = null }` in `ClearOnDestroyLifecycleObserver.onDestroy`. method. Thus, if we happen to open next screen, and exit from it really fast, the viewBinding, that is accessed in onCreateView method will be this undestroyed binding. 

Method call list will be such: 
1. Fragment B: onCreateView
2. Fragment B: BackPressed
2. Fragment A: onDestroyView
3. Fragment A: onCreateView <-- invalid viewBinding here
4. Fragment A: onStart
5. Fragment A: onResume
6. Fragment A: Post OnDestroy (ViewBinding cleared)

**Comment by gmk57** [comment]
I couldn't press Back quickly enough, but it is easily reproducible programmatically, by calling `FragmentManager.popBackStack()` immediately after `commit()`, or from second fragment's `onCreate()`.

**Comment by RuslanDemyanov** [comment]
Also reproduced this error when switching fragments programmatically, is there any way to destroy binding without using a handler?

**Comment by kirich1409** [comment]
> Also reproduced this error when switching fragments programmatically, is there any way to destroy binding without using a handler?

Yes, you can keep reference to the delegate instance and call `clear()` on it

**Comment by kirich1409** [comment]
Need to check the bug with AndroidX Fragment 1.3.0. @midery , please do this and write about results

**Comment by midery** [comment]
> Need to check the bug with AndroidX Fragment 1.3.0. @midery , please do this and write about results

Checked this issue in AndroidX Fragment 1.3.0. Surprisingly, it isn't reproducing anymore.

It happens because the **Fragment.onDestroyView** call is now "postponed" and cancellable in new FragmentManager implementation. 

**Fragment.destroyFragmentView** now is bound to a FragmentTransition, which is used to show fragment's removal. If the transition is not yet completed - Fragment's view won't be destroyed.

Thus, if we will try to press back after the new fragment is added and current fragment is being replaced, it will happen before transition's completion, and the viewBindings would not be cleared.

So, the logs now are showing something like this:
Fragment B: onCreateView
Fragment B: BackPressed
Fragment A: onDestroyView
Fragment A: onCreateView <-- valid viewBinding here
Fragment A: onStart
Fragment A: onResume //on destroy is never called

My advise: update the androidx fragment artifacts and be happy.

**Comment by gmk57** [comment]
> viewBindings would not be cleared

Sorry, but this is exactly the issue. I see no difference between Fragment 1.2.5 & 1.3.0 in this respect.
[Here](https://github.com/gmk57/TestViewBinding2) is a sample project to reproduce. After forward-back navigation the text on screen is wrong, because `FirstFragment`'s `binding` still points to old view during `onViewCreated`.

**Comment by kirich1409** [comment]
> > viewBindings would not be cleared
> 
> Sorry, but this is exactly the issue. I see no difference between Fragment 1.2.5 & 1.3.0 in this respect.
> [Here](https://github.com/gmk57/TestViewBinding2) is a sample project to reproduce. After forward-back navigation the text on screen is wrong, because `FirstFragment`'s `binding` still points to old view during `onViewCreated`.

Please open separate issue with your bug
