### ISSUE TITLE
JCenter and Bintray depreccation

### ISSUE THREAD

**Issue by MikeBarannikov** [kirich1409/ViewBindingPropertyDelegate#39]
Hey there. Thanks for the library.

JCenter and Bintray are being deprecated on May 1st 2021. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Do you plan to migrate your library to MavenCentral?

**Comment by kirich1409** [comment]
Hi. Yes, during this week

**Comment by kirich1409** [comment]
The library has been migrated to Maven Central and new artifacts will be available:
```
com.github.kirich1409:viewbindingpropertydelegate:1.4.2'
com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.4.2'
```
