### ISSUE TITLE
Invalid ViewBinding on quick forward-back navigation in Fragments

### ISSUE THREAD

**Issue by gmk57** [kirich1409/ViewBindingPropertyDelegate#45]
If the Fragment is put in the back stack and then immediately restored with `FragmentManager.popBackStack()`, ViewBinding still points to old view during `onViewCreated`.

[Here](https://github.com/gmk57/TestViewBinding2) is a sample project to reproduce.

I suppose this is the same bug as in #35, but it is still reproducible with Fragments 1.3.0 and ViewBindingPropertyDelegate 1.4.4. So, as [you suggested](https://github.com/kirich1409/ViewBindingPropertyDelegate/issues/35#issuecomment-793380042), I'm opening a new issue.

**Comment by kirich1409** [comment]
The problem connected to work of Fragment ViewLifecycle. The delegate use it's callback to clear value, but if the are not called, you will have the old value

**Comment by gmk57** [comment]
As **midery** [pointed out](https://github.com/kirich1409/ViewBindingPropertyDelegate/issues/35#issue-786769913), this is caused by `mainHandler.post { viewBinding = null }` in `LifecycleViewBindingProperty.clear()`. Calling `viewBinding = null` synchronously eliminates the bug.

**Comment by dmitryskorbovenko** [comment]
I just want to add that LeakCanary reports leaks because of `mainHandler.post { viewBinding = null }` . What the reason was for using mainHandler?

**Comment by kirich1409** [comment]
That's behaviour was added, because `Fragment.onDestroyView()` called after `Lifecycle.onDestroy()`

**Comment by gmk57** [comment]
Yes, I remember well [your article](https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719) on the subject. But it has this unfortunate side-effect.

**Comment by ahulyk** [comment]
subscribing to updates

**Comment by 05nelsonm** [comment]
This issue is plaguing my application as well.

**Comment by d4rken** [comment]
@kirich1409 Your awesome blog post in September about leveraging Kotlin's property mechanics inspired me to write similar code, while not as advanced as your library, the mechanism is the same, and I have encountered similar bugs as you. Recently the issue on quick fragment navigation described in this post by @gmk57 .

I've come up with a solution that seems to work for me, maybe this can also work for your library?

https://github.com/corona-warn-app/cwa-app-android/pull/2913

I `null` the viewBinding before rerunning the initialization if I noticed that the `LifeCycle.onDestroy` triggered, but the `Runnable { viewBinding = null }` didn't.

**Comment by kirich1409** [comment]
@d4rken , I will check your solution. Thanks

**Comment by TemMax** [comment]
Any updates?

**Comment by kirich1409** [comment]
@d4rken , I've checked the solution, but it will help if `getValue()` is called. But if not we will have memory leak

**Comment by kirich1409** [comment]
As a solution for Fragment I've tried

```kotlin
private class FragmentViewBindingProperty<in F : Fragment, out T : ViewBinding>(
    viewBinder: (F) -> T
) : LifecycleViewBindingProperty<F, T>(viewBinder) {

    private var fragmentLifecycleCallbacks: FragmentManager.FragmentLifecycleCallbacks? = null

    override fun getValue(thisRef: F, property: KProperty<*>): T {
        registerFragmentLifecycleCallbacks(thisRef)
        return super.getValue(thisRef, property)
    }

    private fun registerFragmentLifecycleCallbacks(fragment: Fragment) {
        if (fragmentLifecycleCallbacks != null) {
            return
        }

        fragmentLifecycleCallbacks = ClearOnDestroy().also { callbacks ->
            fragment.parentFragmentManager
                .registerFragmentLifecycleCallbacks(callbacks, false)
        }
    }

    override fun clear() {
        super.clear()
        fragmentLifecycleCallbacks = null
    }

    override fun getLifecycleOwner(thisRef: F): LifecycleOwner {
        try {
            return thisRef.viewLifecycleOwner
        } catch (ignored: IllegalStateException) {
            error("Fragment doesn't have view associated with it or the view has been destroyed")
        }
    }

    private inner class ClearOnDestroy : FragmentManager.FragmentLifecycleCallbacks() {

        override fun onFragmentDestroyed(fm: FragmentManager, f: Fragment) {
            // Fix for destroying view for case with issue of navigation
            postClear()
        }
    }
}
```

I don't like that solution, but it must solve the issue with Lifecycle

**Comment by gmk57** [comment]
Another possible approach is described [here](https://gist.github.com/Zhuinden/ea3189198938bd16c03db628e084a4fa#gistcomment-3785693), but I haven't tried it yet.
