### ISSUE TITLE
Not inflating correctly when using CreateMethod.INFLATE

### ISSUE THREAD

**Issue by szaske** [kirich1409/ViewBindingPropertyDelegate#47]
When I attempt to use your library on my Fragments it does not inflate correctly. The layout is squished in the top left corner of my screen. My standard code looks like this:

```
private var binding: FragmentTestBinding? = null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = FragmentTestBinding.inflate(inflater, container, false)
        return binding?.root
    }
```

but it looks like your code, in the INFLATE enum, is making the container null. My guess is that this is what's causing the issue.  Anyway my company currently extends the Fragment class so I'm not able to pass in the XML file into the Fragment as you seem to like doing in your examples.

**Comment by NZeee** [comment]
I have the same problem because of passing `null` as root :(

**Comment by kirich1409** [comment]
How it connected with the library? You use ViewBinding without the library.
