### ISSUE TITLE
Missing ProGuard definitions in vbpd-noreflection

### ISSUE THREAD

**Issue by cdongieux** [kirich1409/ViewBindingPropertyDelegate#48]
There is a ProGuard file in vbpd-full: https://github.com/kirich1409/ViewBindingPropertyDelegate/blob/master/vbpd/vbpd-full/proguard-rules.pro and the gradle.build file use it https://github.com/kirich1409/ViewBindingPropertyDelegate/blob/master/vbpd/vbpd-full/build.gradle

But the ProGuard rules definition are missing in the vbpd-noreflection module which leads to app crash when minification is enabled.

**Comment by kirich1409** [comment]
`vbpd-noreflection` doesn't require ProGuard rules
