### ISSUE TITLE
Getting fragment_fade_enter.xml not found in navigation graph error

### ISSUE THREAD

**Issue by zcelaloglu** [kirich1409/ViewBindingPropertyDelegate#50]
After I upgraded to 1.4.4 from 0.4.1 to avoid crash related to view lifecycle, build started to fail because of it can`t find anim/fragment_fade_enter in navigation graph

AAPT: error: resource anim/fragment_fade_enter not found.

**Comment by kirich1409** [comment]
It connected with some dependencies from AndroidX libraries that upgraded with it. Check AndroidX Core library
