### ISSUE TITLE
How to use in include layout

### ISSUE THREAD

**Issue by wsdydeni** [kirich1409/ViewBindingPropertyDelegate#58]

**Comment by kirich1409** [comment]
No details provided

**Comment by JayGajjar** [comment]
```

        <FrameLayout
            android:id="@+id/frameLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <include layout="@layout/order_list" />
        </FrameLayout>
```

How can i use binding for the layout that are included in my main layout file

**Comment by dev-gvs** [comment]
> ```
> 
>         <FrameLayout
>             android:id="@+id/frameLayout"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             app:layout_behavior="@string/appbar_scrolling_view_behavior">
> 
>             <include layout="@layout/order_list" />
>         </FrameLayout>
> ```
> 
> How can i use binding for the layout that are included in my main layout file

If it's generic layout, without `merge`, then assign id to the included layout:
```
<FrameLayout
            android:id="@+id/frameLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <include android:id="@+id/order_list" layout="@layout/order_list" />
        </FrameLayout>
```
and use it how you would use any other component:
```
binding.order_list...
```

**Comment by kirich1409** [comment]
The library doesn't add any code to a ViewBinding instance. For access included layout ViewBinding contains another instance of ViewBinding. That works in Android Studio 4.2
