### ISSUE TITLE
To reflection or not to reflection

### ISSUE THREAD

**Issue by yoobi** [kirich1409/ViewBindingPropertyDelegate#9]
Hello, It's more of a question than a real issue, 

I'm trying out your amazing library and while I was looking at the README, I've seen it was possible not to use reflection, but I don't really understand the pros/cons of using it or not.

I'm working with `databinding` actually and I wanted to this syntax
`private val binding by viewBinding(FragmentProfileBinding::bind)` but the following error:

```
Property delegate must have a 'getValue(ProfileFragment, KProperty*>)' method. None of the following functions is suitable.
getValue(ProfileFragment, KProperty<*>) defined in by.kirich1409.viewbindingdelegate.ViewBindingProperty
```

Is it because I'm using `databinding` instead of `viewBinding` ?

**Comment by kirich1409** [comment]
Add PR with separate artifact without reflection
https://github.com/kirich1409/ViewBindingPropertyDelegate/pull/11

**Comment by kirich1409** [comment]
Library use reflection to create new instance of `ViewBinding`, specified by class. In next release it will be separated. The possibility use without reflection is faster and doesn't require keep classes
